### ISSUE TITLE
cannot work on mac

### ISSUE THREAD

**Issue by evenlee** [Giai-Ngo/Goldendict-theme#1]
Thanks for the great work @Giai-Ngo , I tried it in my mac, and copy the files into users/myname/.goldenDict and users/myname/.goldenDict/styles, none of them work, do you have advice?

**Comment by evenlee** [comment]
sorry, it works, seem like some system issue of the background
<img width="277" alt="Screenshot 2023-03-17 at 20 02 15" src="https://user-images.githubusercontent.com/4009476/225899275-f9db6587-f85b-4bcf-b216-6d1940a9b299.png">

**Comment by shenlebantongying** [comment]
https://github.com/xiaoyifang/goldendict

This fork doesn't need extra modification. The system's dark mode on macOS just works.
